module: LaunchDarkly
author: LaunchDarkly
author_url: https://launchdarkly.com
github_url: https://github.com/launchdarkly/ios-client-sdk
clean: true
swift_build_tool: spm
readme: README.md
documentation:
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE.txt

copyright: 'Copyright © 2019 Catamorphic Co.'

custom_categories:
  - name: Core Classes
    children:
    - LDClient
    - LDConfig
    - LDUser
    - LDEvaluationDetail

  - name: Flag Change Observers
    children:
    - LDObserverOwner
    - LDChangedFlag
    - LDFlagChangeHandler
    - LDFlagCollectionChangeHandler
    - LDFlagsUnchangedHandler

  - name: Connection Information
    children:
    - ConnectionInformation
    - LDConnectionModeChangedHandler

  - name: Other Types
    children:
    - LDStreamingMode
    - LDFlagValueConvertible
    - LDFlagKey
    - LDInvalidArgumentError
    - LDErrorHandler

  - name: Objective-C Core Interfaces
    children:
    - ObjcLDClient
    - ObjcLDConfig
    - ObjcLDUser
    - ObjcLDChangedFlag

  - name: Objective-C EvaluationDetail Wrappers
    children:
    - ObjcLDBoolEvaluationDetail
    - ObjcLDIntegerEvaluationDetail
    - ObjcLDDoubleEvaluationDetail
    - ObjcLDStringEvaluationDetail
    - ObjcLDArrayEvaluationDetail
    - ObjcLDDictionaryEvaluationDetail

  - name: Objective-C ChangedFlag Wrappers
    children:
    - ObjcLDBoolChangedFlag
    - ObjcLDIntegerChangedFlag
    - ObjcLDDoubleChangedFlag
    - ObjcLDStringChangedFlag
    - ObjcLDArrayChangedFlag
    - ObjcLDDictionaryChangedFlag
