# See test subconfiguration at `LaunchDarkly/LaunchDarklyTests/.swiftlint.yml`

disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - first_where
  - flatmap_over_map_reduce
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - missing_docs
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unused_declaration
  - unused_import
  - vertical_whitespace_closing_braces

included:
  - LaunchDarkly/LaunchDarkly
  - LaunchDarkly/LaunchDarklyTests

excluded:

function_body_length:
  warning: 50
  error: 70

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 1000
  error: 1500

identifier_name:
  min_length: # only min_length
    warning: 3 # only warning
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - url
    - obj
    - key
    - all
    - tag
    - lhs
    - rhs

reporter: "xcode"