disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - force_cast
  - force_try
  - file_length
  - identifier_name
  - large_tuple
  - redundant_optional_initialization
  - type_body_length
  # Disabled opt-in rules from .swiftlint.yml in the project root.
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - missing_docs
  - trailing_closure

opt_in_rules:

excluded:

reporter: "xcode"